apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service-v3
spec:
  selector:
    matchLabels:
      app: client-service-v3
  replicas: 2
  template:
    metadata:
      labels:
        app: client-service-v3
    spec:
      containers:
      - name: client-service-v3
        image: client:6.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80